## 一、什么是张量
张量（tensor）是PyTorch中的基本数据结构，它是一个多维数组。张量可以是向量（一维）、矩阵（二维）或更高维度的数组。在PyTorch中，张量可以用来表示和处理各种数据，包括图像、文本、声音等。在代码中，x是一个向量，也是一个张量。

## 二、张量的创建

In [ ]:
# 导入torch
import torch
# 创建一个向量，在PyTorch中，向量是一维的张量
x = torch.arange(12)
# 访问创建的向量
x

In [5]:
# 使用shape属性来访问张量的形状
x.shape

torch.Size([12])

In [6]:
# 使用numel()函数查看张量的元素总个数
x.numel()

12

要改变张量的形状而不改变其元素数量和元素值，可以调用reshape函数

In [7]:
# 改变为3行4列的矩阵
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [12]:
# 创建元素为全0的三维张量，其中第一个维度的大小为2，第二个维度的大小为3，第三个维度的大小为4。
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
# 也可以创建元素为全1的三维张量
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
# 创建一个包含指定值的二维张量
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [15]:
# 创建一个包含指定值的三维张量
torch.tensor([[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]])

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]])

In [16]:
# 查看该三维张量的形状，其中第一个维度的大小为1，第二个维度的大小为3，第三个维度的大小为4。
torch.tensor([[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]]).shape

torch.Size([1, 3, 4])

## 三、张量的计算