# 线性代数

多维数据是一个纯计算机的概念。而线性代数是一个数学上的概念，本节将介绍线性代数中的基本数学对象、算术和运算，并用数学符号和相应的代码实现来表示它们。

## 一、线性代数的实现

标量由只有一个元素的张量表示，如下示例

In [1]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x +y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

可以将向量视为标量值组成的列表

In [2]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

通过张量的索引来访问任一元素

In [3]:
x[3]

tensor(3)

访问张量的长度

In [4]:
len(x)

4

只有一个轴的张量，形状只有一个元素

In [5]:
x.shape

torch.Size([4])

通过指定两个分量m和n来创建一个形状为m*x的矩阵，如下示例

In [6]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对于对称矩阵（symmetric matrix）来说，A等于其转置：A = A<sup>T</sup>

In [8]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [9]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

就像向量是标量的推广，矩阵是向量的推广一样，我们可以构建具有更多轴的数据结构

In [12]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

给定具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量。

In [13]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone() # 通过内存新分配，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵的按元素乘法成为“哈达玛积”（Hadamard product）数学符号是：⊙

In [14]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [15]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

计算元素的和

In [16]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和

In [17]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

求平均值（用mean或average），求均值等同于求和之后除以元素的个数

In [19]:
A.mean(), A.sum() / A.numel()

(tensor(9.5000), tensor(9.5000))

还可以按某个维度来计算均值

In [20]:
A.mean(axis = 0), A.sum(axis = 0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

计算总和或均值时保持轴数不变

In [21]:
sum_A = A.sum(axis = 1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

通过广播将`A`除以`sum_A`

In [22]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

某个轴计算`A`元素的累积总和

In [23]:
A.cumsum(axis = 0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

这行代码是用来计算数组的累积和（cumulative sum）。其中，axis = 0 表示按照列的方向进行累积求和操作。

具体地，cumsum(axis = 0) 会对数组进行逐列的累积求和操作，返回一个与原数组形状相同的新数组。新数组的每个元素都是原数组中对应列及之前所有元素的累积和。

举个例子，假设有一个二维数组 arr：

```python
arr = [[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]
```

通过执行 arr.cumsum(axis = 0)，会得到以下结果：
```python
[[ 1,  2,  3],
 [ 5,  7,  9],
 [12, 15, 18]]
```

第一列的元素保持不变，第二列的元素等于原数组第一列和第二列元素的和，第三列的元素等于原数组所有三列元素的和。

点积是相同位置的按元素乘积的和

In [24]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

我们可以通过执行按元素乘法，然后进行求和来表示两个向量的点积

In [25]:
torch.sum(x * y)

tensor(6.)

矩阵向量积Ax是一个长度为m的列向量，其中第i<sup>th</sup>是点积a<sub>i</sub><sup>T</sup>X

In [26]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

我们可以将矩阵-矩阵乘法 AB 看作是简单地执行 m 次矩阵-向量积，并将结果拼接在一起，形成一个 n * m 矩阵

In [27]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L<sub>2</sub>范数是向量元素平方和的平方根

In [28]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

L<sub>1</sub>范数是向量元素的绝对值之和

In [29]:
torch.abs(u).sum()

tensor(7.)

矩阵的弗洛贝尼斯范数（Frobenius norm）是矩阵元素的平方和的平方根

In [30]:
torch.norm(torch.ones(4, 9))

tensor(6.)

## 二、按特定轴求和